<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<TargetFramework>net8.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>

		<Jbig2FilterVersion Condition="'$(Jbig2FilterVersion)' == ''">Local</Jbig2FilterVersion>
	</PropertyGroup>

	<ItemGroup Condition="'$(Jbig2FilterVersion)' == 'Local'">
		<ProjectReference Include="..\UglyToad.PdfPig.Filters.Jbig2.PdfboxJbig2\UglyToad.PdfPig.Filters.Jbig2.PdfboxJbig2.csproj" />
	</ItemGroup>

	<ItemGroup Condition="'$(Jbig2FilterVersion)' == 'Latest'">
		<PackageReference Include="PdfPig.Filters.Jbig2.PdfboxJbig2" Version="0.1.16.1" />
	</ItemGroup>
	
	<ItemGroup>
		<PackageReference Include="BenchmarkDotNet" Version="0.15.8" />
	</ItemGroup>

	<ItemGroup>
		<None Include="Assets\**" CopyToOutputDirectory="PreserveNewest" />
	</ItemGroup>

	<ItemGroup>
	  <None Update="Documents\ag46.pdf">
	    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	  </None>
	  <None Update="Documents\GHOSTSCRIPT-687530-0.pdf">
	    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	  </None>
	  <None Update="Documents\GHOSTSCRIPT-688477-0.pdf">
	    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	  </None>
	  <None Update="Documents\GHOSTSCRIPT-690151-0.pdf">
	    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	  </None>
	  <None Update="Documents\GHOSTSCRIPT-690360-0.pdf">
	    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	  </None>
	  <None Update="Documents\jury-summons-guide-eng.pdf">
	    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	  </None>
	  <None Update="Documents\MOZILLA-11518-0.pdf">
	    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	  </None>
	  <None Update="Documents\MOZILLA-8932-0.pdf">
	    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	  </None>
	</ItemGroup>

</Project>
